name: README Actions

on:
  push:
  schedule:
    - cron: '0 22 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  # https://github.com/imkasen/time-progress-bar
  update-progress-bar:
    name: Update the time progress bar
    runs-on: ubuntu-latest
    steps:
      - uses: imkasen/time-progress-bar@master
        with:
          TIME_ZONE: +8
          BLOCKS: ⣀⣤⣶⣿

  # https://github.com/gautamkrishnar/blog-post-workflow
  update-readme-with-blog:
    name: Update the latest blog posts
    if: ${{ always() }}
    needs: update-progress-bar # sequence
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.imkasen.com/atom.xml"
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          committer_username: GitHub Actions[Bot]

  # https://github.com/athul/waka-readme
  update-readme-with-wakatime:
    name: Update the weekly development breakdown
    if: ${{ always() }}
    needs: [update-progress-bar, update-readme-with-blog] # sequence
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TITLE: true
