name: Latest blog post workflow

on:
  push:
  schedule:
    - cron: "0 22 * * *"

jobs:
  # https://github.com/gautamkrishnar/blog-post-workflow
  update-readme-with-blog:
    name: Update the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.imkasen.com/atom.xml"
          # committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          # committer_username: GitHub Actions[Bot]
