# https://github.com/gautamkrishnar/blog-post-workflow
name: Latest blog post workflow

on:
  push:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.imkasen.com/atom.xml"
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          committer_username: GitHub Actions[Bot]
