name: Time progress bar

on:
  push:
  schedule:
    - cron: "0 16 * * *"

jobs:
  # https://github.com/imkasen/time-progress-bar
  update-progress-bar:
    name: Update the time progress bar
    runs-on: ubuntu-latest
    steps:
      - uses: imkasen/time-progress-bar@main
        with:
          TIME_ZONE: +8
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
