name: Time Progress Bar

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  update-progress-bar:
    name: Update this repo's README with Time progress bar
    runs-on: ubuntu-latest
    steps:
      - uses: imkasen/Time-Progress-Bar@master
        with:
          TIME_ZONE: +8
