name: Update Metrics

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  update-metrics:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          # Most used languages
          plugin_languages: yes
          plugin_languages_ignored: jupyter notebook,html,css          
          plugin_languages_details: percentage                         
          # plugin_languages_threshold: 2%   
          # Isometric commit calendar 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year                        
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git add .
          git commit -m "Github action update metrics at `date '+%Y-%m-%d %H:%M:%S'`."
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      
