name: Wakatime

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  # https://github.com/athul/waka-readme
  update-wakatime:
    name: Update the weekly development breakdown
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TITLE: true
